config/routes.rb
Findit::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new', :as => :sign_in
    post 'sign_in' => 'devise/sessions#create', :as => :sign_in
    delete 'sign_out' => 'devise/sessions#destroy', :as => :sign_out
    get 'register' => 'devise/registrations#new'
    post 'register' => 'devise/registrations#create'
  end
  resources :users, :except => [:new, :create]
  resources :allowed_users, :only => :create
  resources :comments
  resources :areas, :except =>[:show]
  resources :projects, :except => [:show]
  resources :tickets do
    collection do
      post 'take'
      get 'show_by_area'
      get 'show_by_project'
    end
  end
  resources :operating_systems, :except => [:show]
  resources :dns_names
  resources :softwares
  resources :locations, :except => [:show]
  resources :buildings, :except => [:show]
  resources :items do
    collection do
      get 'not_checked'
      post 'add_ip'
      get 'remove_ip'
      get 'remove_dns_name'
      get 'mark_as_inventoried'
      get 'surplus'
    end
  end
  resources :reports, :only=>:index do
    collection do
      get :dns
      get :proc_ratings
      get :upgrades
    end
  end
  resources :ips, :except => [:show]
  resources :pages
  resources :installations do
    collection do
      post 'install_software'
      get 'uninstall_software'
    end
  end
  resources :incoming_email, :only=>[:index]
  match "mail", :to=>"incoming_email#index", :as=>"mail"
  root :to=>"items#index", :type=>"Desktop"
end

app/models/dns_name.rb
class DnsName < ActiveRecord::Base
  attr_accessible :name
  belongs_to :item
  
  def to_s
    name
  end
end

app/controllers/dns_names_controller.rb
class DnsNamesController < ApplicationController
  
  def index
    @dns_names = DnsName.all
  end
  
  def show
    @dns_name = DnsName.find(params[:id])
  end
  
  def new
    @dns_name = DnsName.new
  end
  
  def create
    @dns_name = DnsName.new(params[:dns_name])
    if @dns_name.save
      flash[:notice] = "Successfully created dns name."
      redirect_to @dns_name
    else
      render :action => 'new'
    end
  end
  
  def edit
    @dns_name = DnsName.find(params[:id])
  end
  
  def update
    @dns_name = DnsName.find(params[:id])
    if @dns_name.update_attributes(params[:dns_name])
      flash[:notice] = "Successfully updated dns name."
      redirect_to @dns_name
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @dns_name = DnsName.find(params[:id])
    @dns_name.destroy
    flash[:notice] = "Successfully destroyed dns name."
    redirect_to dns_names_url
  end
end

app/helpers/dns_names_helper.rb
module DnsNamesHelper
end

app/views/dns_names/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.dns_name.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
	<%= link_to "Cancel", dns_names_path,:class => "button" %> 
</div>

app/views/dns_names/_sidebar.html.erb
<div class="block">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/dns_names/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", dns_names_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_dns_name_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_dns_name_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> DnsName</h2>
    <div class="inner">
      <%= form_for @dns_name, :url => dns_name_path(@dns_name), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/dns_names/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", dns_names_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_dns_name_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> DnsNames</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.dns_name.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @dns_names.each do |dns_name| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= dns_name.id %>
          </td>
                    <td>
            <%= link_to dns_name.name, dns_name_path(dns_name) %>
          </td>
                    <td>
            <%= dns_name.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", dns_name_path(dns_name) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_dns_name_path(dns_name) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", dns_name_path(dns_name), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/dns_names/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", dns_names_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_dns_name_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  DnsName</h2>
    <div class="inner">
      <%= form_for :dns_name, :url => dns_names_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/dns_names/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", dns_names_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_dns_name_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", dns_name_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.dns_name.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @dns_name.name %>
        </p>
      <div class="wat-cf">
        <%= link_to "#{image_tag("web-app-theme/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}")} #{t("web-app-theme.edit", :default=> "Edit")}", edit_dns_name_path(@dns_name), :class => "button" %> 
        <%= link_to "#{image_tag("web-app-theme/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}")} #{t("web-app-theme.delete", :default => "Delete")}", dns_name_path(@dns_name), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>