config/routes.rb
Findit::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new', :as => :sign_in
    post 'sign_in' => 'devise/sessions#create', :as => :sign_in
    delete 'sign_out' => 'devise/sessions#destroy', :as => :sign_out
    get 'register' => 'devise/registrations#new'
    post 'register' => 'devise/registrations#create'
  end
  resources :users, :except => [:new, :create]
  resources :allowed_users, :only => :create
  resources :comments
  resources :areas, :except =>[:show]
  resources :projects, :except => [:show]
  resources :tickets do
    collection do
      post 'take'
      get 'show_by_area'
      get 'show_by_project'
    end
  end
  resources :operating_systems, :except => [:show]
  resources :dns_names
  resources :softwares
  resources :locations, :except => [:show]
  resources :buildings, :except => [:show]
  resources :items do
    collection do
      get 'not_checked'
      post 'add_ip'
      get 'remove_ip'
      get 'remove_dns_name'
      get 'mark_as_inventoried'
      get 'surplus'
    end
  end
  resources :reports, :only=>:index do
    collection do
      get :dns
      get :proc_ratings
      get :upgrades
    end
  end
  resources :ips, :except => [:show]
  resources :pages
  resources :installations do
    collection do
      post 'install_software'
      get 'uninstall_software'
    end
  end
  resources :incoming_email, :only=>[:index]
  match "mail", :to=>"incoming_email#index", :as=>"mail"
  root :to=>"items#index", :type=>"Desktop"
end

app/views/admin/_bottom_admin.html.erb
</div>
</div>
</div>
<% content_for :sidebar, render(:partial=>'admin/sidebar') %>

app/views/admin/_navigation.html.erb
<%= tab_link "Areas", areas_path, "Areas",params[:controller], "first" %>
<%= tab_link "IPS", ips_path, "ips", params[:controller] %>
<%= tab_link "Users", users_path, "Users", params[:controller] %>
<%= tab_link "Operating Systems", operating_systems_path, "Operating_systems", params[:controller] %>
<%= tab_link "Projects", projects_path, "Projects", params[:controller] %>
<%= tab_link "Reports", reports_path, "Reports", params[:controller] %>
<%= tab_link "Buildings", buildings_path, "Buildings", params[:controller] %>
<%= tab_link "Locations", locations_path, "Locations", params[:controller] %>

app/views/admin/_sidebar.html.erb
<div class="block">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/_top_admin.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
		<%= render :partial=>"admin/navigation" %>
    </ul>
  </div>          
  <div class="content">          
    <div class="inner">

app/views/admin/index.html.erb
   <%= render :partial=>"top_admin"  %>
   <%= render :partial=>"bottom_admin" %>