config/routes.rb
Findit::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new', :as => :sign_in
    post 'sign_in' => 'devise/sessions#create', :as => :sign_in
    delete 'sign_out' => 'devise/sessions#destroy', :as => :sign_out
    get 'register' => 'devise/registrations#new'
    post 'register' => 'devise/registrations#create'
  end
  resources :users, :except => [:new, :create]
  resources :allowed_users, :only => :create
  resources :comments
  resources :areas, :except =>[:show]
  resources :projects, :except => [:show]
  resources :tickets do
    collection do
      post 'take'
      get 'show_by_area'
      get 'show_by_project'
    end
  end
  resources :operating_systems, :except => [:show]
  resources :dns_names
  resources :softwares
  resources :locations, :except => [:show]
  resources :buildings, :except => [:show]
  resources :items do
    collection do
      get 'not_checked'
      post 'add_ip'
      get 'remove_ip'
      get 'remove_dns_name'
      get 'mark_as_inventoried'
      get 'surplus'
    end
  end
  resources :reports, :only=>:index do
    collection do
      get :dns
      get :proc_ratings
      get :upgrades
    end
  end
  resources :ips, :except => [:show]
  resources :pages
  resources :installations do
    collection do
      post 'install_software'
      get 'uninstall_software'
    end
  end
  resources :incoming_email, :only=>[:index]
  match "mail", :to=>"incoming_email#index", :as=>"mail"
  root :to=>"items#index", :type=>"Desktop"
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :login, :first_name, :last_name,:email
  has_many :items
  has_many :tickets
  belongs_to :area
  has_many :comments

  scope :workers, where(:can_login => true)

  validates_uniqueness_of :login, :if=>lambda{!self.login.nil?}

  def full_name
    [first_name, last_name].join(" ")
  end

  def name
    if full_name
      full_name
    elsif email
      email
    else
      "No Info"
    end
  end
  
  def reverse_name
    [last_name, first_name].join(", ")
  end

  def to_s
    name
  end

  def full_info
    [first_name, last_name, login].join(" ")  
  end


  def self.find_or_create_by_email(email)
    user = User.find_by_email(email)
    if user
      return user
    else
      user = User.create(:email=>email, :first_name=>"No", :last_name=>"Name")
      user.login = email.split("@")[0]
      user.save_with_random_password
    end
    user
  end

  #devise methods
  def active_for_authentication?
    super && can_login?
  end

  def inactive_message
    if !can_login?
      :not_approved
    else
      super
    end
  end

  def save_with_random_password
    random_string = SecureRandom.hex
    self.password = random_string
    self.password_confirmation = random_string
    save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order "last_name"
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated user."
      redirect_to @user
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Successfully destroyed user."
    redirect_to users_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages',:target => @user  %>

  <%= f.input :email %>
  <%= f.input :login %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :can_login %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_sidebar.html.erb
<div class="block">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/users/edit.html.erb
<%- model_class = @user.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>E-mail</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', user_path(user), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          <%= link_to 'Allow Sign In', allowed_users_path(:id => user.id),
            :method => :post,
            :confirm => 'Are you sure you want to allow this user to sign in?',
            :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New', new_user_path, :class => 'btn btn-primary' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<ul class="unstyled">
  <li>Login: <%= @user.login %></li>
  <li>Email: <%= @user.email %></li>
</ul>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>