config/routes.rb
Findit::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new', :as => :sign_in
    post 'sign_in' => 'devise/sessions#create', :as => :sign_in
    delete 'sign_out' => 'devise/sessions#destroy', :as => :sign_out
    get 'register' => 'devise/registrations#new'
    post 'register' => 'devise/registrations#create'
  end
  resources :users, :except => [:new, :create]
  resources :allowed_users, :only => :create
  resources :comments
  resources :areas, :except =>[:show]
  resources :projects, :except => [:show]
  resources :tickets do
    collection do
      post 'take'
      get 'show_by_area'
      get 'show_by_project'
    end
  end
  resources :operating_systems, :except => [:show]
  resources :dns_names
  resources :softwares
  resources :locations, :except => [:show]
  resources :buildings, :except => [:show]
  resources :items do
    collection do
      get 'not_checked'
      post 'add_ip'
      get 'remove_ip'
      get 'remove_dns_name'
      get 'mark_as_inventoried'
      get 'surplus'
    end
  end
  resources :reports, :only=>:index do
    collection do
      get :dns
      get :proc_ratings
      get :upgrades
    end
  end
  resources :ips, :except => [:show]
  resources :pages
  resources :installations do
    collection do
      post 'install_software'
      get 'uninstall_software'
    end
  end
  resources :incoming_email, :only=>[:index]
  match "mail", :to=>"incoming_email#index", :as=>"mail"
  root :to=>"items#index", :type=>"Desktop"
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    
  end
  
  def dns
    @war_items = Item.has_ip.war
    @mccomas_items = Item.has_ip.mccomas
    render :action=>"dns", :layout=>false
  end
  
  
  def proc_ratings
    @items = Item.proc_ratings
  end
  
  def upgrades
    #get the year first
    this_year = Time.now.year.to_s
    next_year = Time.now.year+1
    next_year = next_year.to_s
    six_years_ago = Time.now.year-6
    six_years_ago = six_years_ago.to_s
    five_years_ago = Time.now.year-5
    five_years_ago = five_years_ago.to_s
    four_years_ago = Time.now.year-4
    four_years_ago = four_years_ago.to_s
    #first we want to see the computers that are priority 1 that expire this year
    @priority1_this_year = Item.by_priority(1).warranty_ending_in_year(this_year).in_use
    #then we want to see the computers that are priority 1 that expire next year
    @priority1_next_year = Item.by_priority(1).warranty_ending_in_year(next_year).in_use    
    #then we want to see that computers that are priority 2 that were bought more than 6 years ago this year
    @priority2_this_year = Item.by_priority(2).computers_purchased_in(six_years_ago).in_use
    #then we want to see that computers that are priority 2 that were bought more than 6 years ago next year
    @priority2_next_year = Item.by_priority(2).computers_purchased_in(five_years_ago).in_use
    #priority 1 bought more than 4 years ago
    @priority1_older = Item.by_priority(1).computers_purchased_in(four_years_ago).in_use
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_items.html.erb
<table class="table pretty">
  <tr>
   		<th>Name</th>
	 	<th>Make/Model</th>
		<th>User</th>
		<th>Location</th>
		<th>Purchase Date</th>
		<th>Warranty Expiration</th>
		
  </tr>
  <% items.each do |item| -%>
  <tr class="<%= cycle("odd", "even") %>">
	<td><%= link_to item.name, item_path(item) %></td>
	<td><%= item.make_and_model %></td>
	<td><%= item.user.full_name unless item.user.blank? %></td>
	<td><%=  item.location.short_location unless item.location.blank? %></td>
	<td><%= item.purchased_at.to_s(:long) unless item.purchased_at.blank? %></td>
	<td><%= item.warranty_expires_at.to_s(:long) unless item.purchased_at.blank? %></td>
  </tr>          
  <% end -%>
</table>

app/views/reports/_navigation.html.erb
<li class="first"><%= link_to "DNS", :controller=>"reports", :action=>"dns"  %></li>
<li><%= link_to "Processor Ratings", :controller=>"reports", :action=>"proc_ratings" %></li>
<li><%= link_to "Upgrades", :controller=>"reports", :action=>"upgrades" %></li>

app/views/reports/_sidebar.html.erb
<div class="block">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/reports/dns.erb
#  $Header: /var/named/share/Database-RCS/recsports.hosts,v 1.15 2009/04/21 12:20:34 walklet Exp $ <br />
nsdata.recsports.vt.edu::nomail::: <br />

#War Memorial Hall - 128.173.108.*<br />
<% @war_items.each do |i| %>
<%= "#{i.dns_safe_name}.recsports.vt.edu" %>:<%= i.print_ip %>::<%= i.print_dns_names %>::
<br />
<% end %>
#McComas Hall - 128.173.129.*<br />
<% @mccomas_items.each do |i| %>
<%= "#{i.dns_safe_name}.recsports.vt.edu" %>:<%= i.print_ip %>::<%= i.print_dns_names %>::
<br />
<% end %>

app/views/reports/index.html.erb
  <table>
    <tr>
      <th>Report Name</th>
      <th>Description</th>
    </tr>
    <tr class="odd">
      <td><%= link_to "DNS", dns_reports_path %></td>
      <td><p>This is the report that is used for updating the DNS records with hostmaster.  **Note** this will take you a text based page with no theme </p></td>
    </tr>
    <tr class="even">
      <td><%= link_to "Upgrades", upgrades_reports_path %></td>
      <td><p>This report allows you to see what items are going to need to be upgraded next according to the Rec Sports upgrade standards</p></td>
    </tr>
  </table>

app/views/reports/proc_ratings.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
		<%= render :partial=> "navigation" %>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= h @title %></h2>

    <div class="inner">
      <table class="table">
        <tr>
            <th>
            	<%= t("activerecord.attributes.item.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          	</th>
		 	<th>Make/Model</th>
			<th>Type</th>
			<th>Location</th>
			<th>Proc</th>
			<th>Proc Rating</th>
			<th>Ram</th>
			

        </tr>
        <% @items.each do |item| -%>
        <tr class="<%= cycle("odd", "even") %>">
           	<td><%= link_to item.name, item_path(item) %></td>
			<td><%= h item.make_and_model %></td>
			<td><%= h item.short_type unless item.type_of_item.blank? %></td>
            <td><%= h item.location.short_location unless item.location.blank? %></td>
            <td><%= h item.short_processor unless item.processor.blank? %></td>
            <td><%= h item.processor_rating unless item.processor_rating.blank? %></td>
			<td><%= h number_to_human_size(item.ram) unless item.ram.blank? %></td>
			

       
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/reports/upgrades.html.erb
<%= render :partial=>"admin/top_admin" %>
<h2>Upgrades Report</h2>
<h3>Priority 1 Computers that the warranty expires this year</h3>
<%= render :partial=>"items", :locals=>{:items=>@priority1_this_year} %>
<h3>Priority 1 Computers that the warranty expires next year</h3>
<%= render :partial=>"items", :locals=>{:items=>@priority1_next_year} %>
<h3>Priority 2 computers that are older than 6 years this year</h3>
<%= render :partial=>"items", :locals=>{:items=>@priority2_this_year} %>
<h3>Priority 2 computers that are older than 6 years next year</h3>
<%= render :partial=>"items", :locals=>{:items=>@priority2_next_year} %>
<h3>Priority 1 Computers that are older than 4 years this year</h3>
<%= render :partial=>"items", :locals=>{:items=>@priority1_older} %>
<%= render :partial=>"admin/bottom_admin" %>